import type { Question } from "./types"

export const QUESTIONS: Question[] = [
  {
    id: "j1-any",
    day: "J1",
    prompt: "En TypeScript strict, à quoi sert vraiment `any` ?",
    choices: [
      "Il convertit automatiquement la valeur en number",
      "Il coupe le contrôle de type sur cette valeur",
      "Il est obligatoire pour typer les props React",
      "C’est un alias plus sûr de `unknown`",
    ],
    correctIndex: 1,
    timeLimitMs: 25000,
  },
  {
    id: "j1-readonly",
    day: "J1",
    prompt: "Sur `VehicleBase`, `readonly id` signifie :",
    choices: [
      "L’id est optionnel",
      "L’id est chiffré au runtime",
      "TypeScript refuse `vehicle.id = \"x\"`",
      "L’id peut changer tant que le nom reste identique",
    ],
    correctIndex: 2,
    timeLimitMs: 25000,
  },
  {
    id: "j1-kind",
    day: "J1",
    prompt: "Une union discriminante se reconnaît surtout à :",
    choices: [
      "Tous les champs métier mis en optionnel (`?`)",
      "Un `as CrewedVehicle` dans chaque branche",
      "Un `if (vehicle.payloadKg)` sur un objet fourre-tout",
      "Un champ `kind` littéral distinct par variante",
    ],
    correctIndex: 3,
    timeLimitMs: 28000,
  },
  {
    id: "j1-never",
    day: "J1",
    prompt: "`assertNever(vehicle)` dans le `default` d’un `switch (kind)` :",
    choices: [
      "Fait échouer la compilation si une variante n’est pas traitée",
      "Ignore silencieusement les cas oubliés",
      "Convertit le véhicule en string",
      "Est un hook React",
    ],
    correctIndex: 0,
    timeLimitMs: 28000,
  },
  {
    id: "j1-buffer",
    day: "J1",
    prompt: "Un `Buffer<T>` immuable : que doit faire `pushToBuffer` ?",
    choices: [
      "Muter `buffer.items` avec `.push`",
      "Retourner `any[]` pour rester flexible",
      "Retourner un nouveau buffer, l’ancien `items` inchangé",
      "Accepter une `Alert` dans un buffer de carburant",
    ],
    correctIndex: 2,
    timeLimitMs: 28000,
  },
  {
    id: "j2-key",
    day: "J2",
    prompt: "Dans une liste de véhicules, la `key` correcte est :",
    choices: [
      "L’index du `.map`",
      "`vehicle.id`",
      "`Math.random()`",
      "Le nom du véhicule",
    ],
    correctIndex: 1,
    timeLimitMs: 22000,
  },
  {
    id: "j2-derived",
    day: "J2",
    prompt: "Pour filtrer / trier la flotte, la bonne approche est :",
    choices: [
      "`useEffect` + `setFilteredVehicles`",
      "Calculer `visibleVehicles` pendant le rendu",
      "Muter `vehicles[i].hidden = true`",
      "Lire l’input via `document.getElementById`",
    ],
    correctIndex: 1,
    timeLimitMs: 28000,
  },
  {
    id: "j2-mutate",
    day: "J2",
    prompt: "`vehicle.status = \"maintenance\"` puis `setVehicles(vehicles)` :",
    choices: [
      "C’est la mise à jour immuable recommandée",
      "Crée automatiquement une copie profonde",
      "Mute la même référence : React peut ignorer le rendu",
      "Fonctionne uniquement avec `key={index}`",
    ],
    correctIndex: 2,
    timeLimitMs: 28000,
  },
  {
    id: "j2-controlled",
    day: "J2",
    prompt: "Un champ de recherche contrôlé, c’est :",
    choices: [
      "`value` + `onChange` branchés sur un state",
      "`defaultValue` tout seul",
      "Un `useEffect` qui lit l’input après coup",
      "`document.querySelector(\"input\").value`",
    ],
    correctIndex: 0,
    timeLimitMs: 25000,
  },
  {
    id: "j2-children",
    day: "J2",
    prompt: "Un `Panel` avec `children` doit :",
    choices: [
      "Importer `vehicles.ts` pour connaître Aquila",
      "Exposer `showHeader: boolean` plutôt qu’un header enfant",
      "Organiser le cadre sans connaître le métier",
      "Dupliquer le JSX de section trois fois",
    ],
    correctIndex: 2,
    timeLimitMs: 25000,
  },
  {
    id: "j3-nav",
    day: "J3",
    prompt: "Pour changer de module (Flotte, Missions, Contrôle) :",
    choices: [
      "`useState(\"fleet\")` et des boutons qui swap le JSX",
      "Quatre barres de nav recopiées dans chaque page",
      "`window.location.href` obligatoire à chaque clic",
      "`Link` / `NavLink` : l’URL change, F5 et Précédent marchent",
    ],
    correctIndex: 3,
    timeLimitMs: 28000,
  },
  {
    id: "j3-404",
    day: "J3",
    prompt: "`/fleet/unknown` et `/pizza-on-mars`, c’est :",
    choices: [
      "La même page 404",
      "Route OK / ressource absente vs aucune route",
      "Deux crashs JavaScript attendus",
      "Deux redirections silencieuses vers `/fleet`",
    ],
    correctIndex: 1,
    timeLimitMs: 28000,
  },
  {
    id: "j3-params",
    day: "J3",
    prompt: "`useParams()` pour `:vehicleId` :",
    choices: [
      "Garantit un véhicule valide",
      "Est une entrée externe : absente, mal encodée, ou inconnue",
      "Remplace les `key` de liste",
      "Ne fonctionne qu’avec un `useState` du module",
    ],
    correctIndex: 1,
    timeLimitMs: 25000,
  },
  {
    id: "j4-effect-loop",
    day: "J4",
    prompt: "`useEffect(() => { fetch().then(setVehicles) }, [vehicles])` :",
    choices: [
      "C’est le pattern recommandé",
      "Boucle : l’effet écrit `vehicles`, qui relance l’effet",
      "Remplace `AbortController`",
      "Est le bon endroit pour filtrer la liste",
    ],
    correctIndex: 1,
    timeLimitMs: 28000,
  },
  {
    id: "j4-abort",
    day: "J4",
    prompt: "Un `AbortError` pendant le fetch, c’est :",
    choices: [
      "Une panne sol à afficher avec « Réessayer »",
      "Un HTTP 500",
      "L’annulation d’une requête, pas une erreur métier",
      "Un JSON `[]`",
    ],
    correctIndex: 2,
    timeLimitMs: 25000,
  },
  {
    id: "j4-assert",
    day: "J4",
    prompt: "`const data = (await response.json()) as Vehicle[]` :",
    choices: [
      "Valide le JSON à l’exécution",
      "Documente une attente, ne valide rien",
      "Remplace le test `response.ok`",
      "Convertit `fuel_ratio` en `fuelPercent`",
    ],
    correctIndex: 1,
    timeLimitMs: 28000,
  },
  {
    id: "j4-empty",
    day: "J4",
    prompt: "Tableau JSON `[]` vs HTTP 500 :",
    choices: [
      "Les deux affichent « Signal perdu »",
      "`[]` = succès vide ; 500 = erreur + retry",
      "Empty doit retry le réseau",
      "500 doit afficher `0 %` de carburant",
    ],
    correctIndex: 1,
    timeLimitMs: 28000,
  },
  {
    id: "j4-fuel",
    day: "J4",
    prompt: "Hermes arrive sans `fuel_ratio`. L’écran doit :",
    choices: [
      "Afficher `0 %`",
      "Crasher la fiche",
      "Mentir avec un réservoir plein",
      "Dire « donnée indisponible », jamais `0 %`",
    ],
    correctIndex: 3,
    timeLimitMs: 25000,
  },
]
